删除仓库

diff --git a/s2i/bin/assemble b/s2i/bin/assemble
--- a/s2i/bin/assemble
+++ b/s2i/bin/assemble
@@ -152,9 +152,9 @@ if [ -f "$LOCAL_SOURCE_DIR/pom.xml" ]; then
   # optionally clear the local maven repository after the build
   clear_maven_repository
   #清理所有源码
-  #rm -rf /opt/app-root/source/?/.m2/repository/*
-  #rm -rf /opt/app-root/source/src/*
-  #rm -rf /opt/app-root/source/target/*
+  rm -rf /opt/app-root/source/?/.m2/repository
+  rm -rf /opt/app-root/source/src
+  rm -rf /opt/app-root/source/target
 
   popd &> /dev/null
 else
@@ -172,11 +172,11 @@ fi
 RUN_JAR_COUNT=$(ls ${DEPLOY_DIR}/*${APP_SUFFIX}.jar | wc -l)
 
 if [ ${RUN_JAR_COUNT} -eq 1 ]; then
-  #echo "[INFO] Boot-JAR=${DEPLOY_DIR}/${APP_SUFFIX}.jar"
-  echo "[INFO] Copying ${DEPLOY_DIR}/*${APP_SUFFIX}.jar into ${DEPLOY_DIR}/app.jar"
-  cp ${DEPLOY_DIR}/*${APP_SUFFIX}.jar ${DEPLOY_DIR}/app.jar
-  [ ! -f ${DEPLOY_DIR}/app.jar ] && echo "Application could not be properly built." && exit 1
-  echo "[INFO] Application jar file is located in ${DEPLOY_DIR}/app.jar"
+  echo "[INFO] Boot-JAR=${DEPLOY_DIR}/${APP_SUFFIX}.jar"
+  #echo "[INFO] Copying ${DEPLOY_DIR}/*${APP_SUFFIX}.jar into ${DEPLOY_DIR}/app.jar"
+  #cp ${DEPLOY_DIR}/*${APP_SUFFIX}.jar ${DEPLOY_DIR}/app.jar
+  #[ ! -f ${DEPLOY_DIR}/app.jar ] && echo "Application could not be properly built." && exit 1
+  #echo "[INFO] Application jar file is located in ${DEPLOY_DIR}/app.jar"
 elif [ ${RUN_JAR_COUNT} -eq 0 ]; then
  echo "[ERROR] No app.jar file located in ${DEPLOY_DIR}, APP_SUFFIX is ${APP_SUFFIX}"
  exit 1
